_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR: "../outputs/output4"
MODEL:
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_101_FPN_3x/137851257/model_final_f6e8b1.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("truck_train",)
  TEST: ("truck_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  WARMUP_ITERS: 2000
